#config values for setting up test runs only

#used to find whether the specs are being run in a working
#directory within the test environment
test_root_match: 'spec'

#this should match the directory given in the wraith configs
directory:
  - 'shots'

#store of test images
image_store_dir: 'image_store'

#store of thumbnail images created during tests
thumbnails_dir: 'thumbnails'

#these should match the path directories in the wraith configs
paths:
  home: /
  uk_index: /uk

#example files for image manipulation methods
example_files:
  - 'shots/home/1024_selenium_local_desktop_mac_chrome_base.png'
  - 'shots/home/1024_selenium_local_desktop_mac_chrome_compare.png'
  - 'shots/home/768_selenium_local_desktop_mac_chrome_base.png'
  - 'shots/home/768_selenium_local_desktop_mac_chrome_compare.png'

#base and compare example files for creating diffs from - url comparison
base_compare_file_examples_url_comparison:
  - 'shots/home/320_selenium_local_desktop_mac_chrome_base.png'
  - 'shots/home/320_selenium_local_desktop_mac_chrome_compare.png'
  - 'shots/home/320_selenium_local_desktop_mac_firefox_base.png'
  - 'shots/home/320_selenium_local_desktop_mac_firefox_compare.png'

#base and compare example files for creating diffs from - browser comparison
base_compare_file_examples_browser_comparison:
  - 'shots/home/320_selenium_local_desktop_mac_chrome_base.png'
  - 'shots/home/320_selenium_local_desktop_mac_chrome_compare.png'
  - 'shots/home/320_selenium_local_desktop_mac_firefox_compare.png'
  - 'shots/home/320_selenium_local_desktop_mac_safari_compare.png'

#different wraith config files to load depending on type of run - each config is a feature scenario
wraith_configs:
  test_webkit_url_config: 'test_phantomjs_url_desktop_config'
  test_selenium_url_config: 'test_selenium_url_desktop_config'
  test_selenium_browser_config: 'test_selenium_browser_desktop_config'
  test_selenium_grid_browser_config: 'test_selenium_grid_browser_config'
  test_selenium_grid_advanced_crop_config: 'test_selenium_grid_advanced_crop_config'

#test expectations
test_expectations:
  test_engine: 'selenium'
  engine_mode:
    default: 'local'
    local: 'local'
    selenium_grid: 'grid'
  shots_directory: 'shots'
  snap_directory: 'javascript/snap.js'
  thumbnails_directory: 'thumbnails_dir'
  image_store_dir: 'image_store_dir'
  timeout: 20
  width_array:
    desktop: [320, 600, 768, 1024, 1280]
    device: [1024]
  base_browser: chrome
  base_types:
    url: 'url'
    browser: 'browser'
  domains:
    base: 'http://www.live.bbc.co.uk/news'
    compare: 'http://www.live.bbc.co.uk/russian'
  domain_labels:
    base: 'base'
    compare: 'compare'
  file_name: 'shots/home/320_selenium_local_desktop_linux_firefox_base.png'
  spider_days: [10]
  fuzz: '20%'
  driver_suites:
    phantomjs: 'webkit'
    selenium: 'standard'
  suites:
    standard: ["safari", "chrome", "firefox"]
    webkit: ['phantomjs']
  browser_devices:
    android:
      device:
    safari:
      desktop:
    chrome:
      desktop:
    firefox:
      desktop:
    ie:
      desktop:
  base_type_browser_device_file_count:
    url:
      phantomjs:
        desktop: 15
      chrome:
        desktop: 15
      firefox:
        desktop: 15
      safari:
        desktop: 15
        device: 3
    browser:
      chrome:
        desktop: 15
      firefox:
        desktop: 10
      safari:
        desktop: 10
  thumbnails_file_count: 45
  crop_args: [10,20,30,40]
  height_of_file: 748
  widths_of_files: [1024,1024,768,768]
  extn_diff_png: '/*diff.png'
  extn_data_txt: '/*data.txt'
  diff_png_count: 15
  data_txt_count: 15
  base_compare_file_examples_url_comparison:
    base:
    - 'shots/home/320_selenium_local_desktop_mac_chrome_base.png'
    compare:
    - 'shots/home/320_selenium_local_desktop_mac_chrome_compare.png'
  base_compare_file_examples_browser_comparison:
      base:
      - 'shots/home/320_selenium_local_desktop_mac_chrome_base.png'
      compare:
      - 'shots/home/320_selenium_local_desktop_mac_chrome_compare.png'
      - 'shots/home/320_selenium_local_desktop_mac_firefox_compare.png'
      - 'shots/home/320_selenium_local_desktop_mac_safari_compare.png'
  default_screen_height: 1000
  default_wait_until_element: comp-most-popular
  os_string:
    grid: 'Linux'
    local: ['windows','mac','linux','unix']
  capabilities_array:
    - :url: 'http://blah.com'
      :os: 'linux'
  default_parameters:
    :url:
    :capabilities:
      :version:
      :platform:
  grid_url: 'http://localhost:4444'