#Selenium Engine option

#change this line based on which suite of browsers you want to run
#better to pass as a command line argument when have time to refactor
suite: "standard"

#define different suites of browsers here
suites:
  webkit: ["phantomjs"]
  standard: ["safari"]
  # gecko: "slimerjs"

#define different engines/drivers to run your browser suites here - e.g. selenium
engine:
  webkit: ""
  standard: "selenium"

#set the devices you want to run each browser in your suite on here.
#you can have 'desktop', 'device', or both
browser_devices:
  safari: ['device']

#If you want to have multiple snapping files, set the file name here
snap_file:
  webkit: "javascript/snap.js"
  standard: ""

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

#thumbnail images subdirectory name
thumbnail_directory: thumbnails

# if you are using url comparison, set the url: base: and url: compare: values
# if using browser comparison, set the url: compare: value
# when using browser-based comparison, always leave the base value blank, as we only use the comparison value
domains:
  url:
    base: "http://www.live.bbc.co.uk/news"
    compare: "http://www.live.bbc.co.uk/russian"
  browser:
    compare:

base_browser:

#Type screen widths below, here are a couple of examples
screen_widths:
  desktop:
    - 320
    - 600
    - 768
    - 1024
    - 1280
  device:
    - 1024

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  uk_index: /uk

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10


###################################################################
#
# SELENIUM ONLY OPTIONS BELOW HERE
#
###################################################################

#page load timeout
timeout: 20

#base type - either 'browser' or 'url'.
#browser base type will compare a given url using a browser as a base
#domain base type will use a url as the basis for comparison against a second url
base_type: url

#set this flag to true if using browser based comparison and you wish to compare
#the base browser to itself. This can be useful to check for page differences caused
#by loading or other instabilities
compare_base_to_base: false

#base type - either 'browser' or 'url'.
#browser base type will compare a given url using a browser as a base.
#url base type will use a url as the basis for comparison against a second url
base_type: browser

#set this if you are using browser type based comparison
base_browser:

#set this to get selenium to wait until a certain page element is displayed
wait_until_element: comp-most-popular

#very annoyingly and weirdly, selenium often interprets screenshot sizes different from those
#stipulated in your window dimensions. Offset behaviour seems inconsistent between browsers, browser versions and
#between different widths, so you will probably have to set some of these values by inspection of the image gallery
screenshot_bias:
  width:
    chrome:
      desktop:
        320: 0
        600: 0
        768: 0
        1024: 0
        1280: 0
      device:
        1024: 0
    firefox:
      desktop:
        320: 15
        600: 15
        768: 15
        1024: 15
        1280: 15
      device:
        1024: 15
    safari:
      desktop:
        320: 15
        600: 15
        768: 15
        1024: 15
        1280: 15
      device:
        1024: 15

###################################################################
#
# SELENIUM GRID ONLY OPTIONS BELOW HERE
#
###################################################################