#Headless browser option

#change this line based on which suite of browsers you want to run
#better to pass as a command line argument when have time to refactor
suite: "webkit"

#define different suites of browsers here
suites:
  webkit: ["phantomjs"]
  standard: ["safari", "chrome", "firefox"]
  # gecko: "slimerjs"

#define different engines/drivers to run your browser suites here - e.g. selenium
engine:
  webkit:
  standard: "selenium"

#engine_mode - set to 'grid' if using a selenium grid, defaults to 'local'
engine_mode:

options:
  webkit: ""

#If you want to have multiple snapping files, set the file name here
snap_file:
  webkit: "javascript/snap.js"
  standard: ""

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

#thumbnail images subdirectory name
thumbnail_directory: thumbnails

#cropped images subdirectory name
crops_directory: crops

#base type - either 'browser' or 'url'.
#browser base type will compare a given url using a browser as a base
#domain base type will use a url as the basis for comparison against a second url.
#phantomJS is always base_type=url
base_type: url

# if you are using url comparison, set the url: base: and url: compare: values
# if using browser comparison, set the url: compare: value
domains:
  url:
    base: "http://www.live.bbc.co.uk/news"
    compare: "http://www.live.bbc.co.uk/russian"
  browser:
    base:
    compare:

#Type screen widths below, here are a couple of examples
screen_properties:
  desktop:
    - 320
    - 600
    - 768
    - 1024
    - 1280
  device:
    - 1024

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  uk_index: /uk

#you can define some default parameters to pass to the selenium driver here,
#can also leave blank as all optional, but don't delete the key structure
#leave blank when using phantomJS
default_parameters:
  :url:
  :capabilities:
    :version:
    :platform:

#if you have just set screen widths in screen_dimensions, you can set a generic height for the screen here
default_screen_height: 1000

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10

###################################################################
#
# SELENIUM ONLY OPTIONS BELOW HERE
#
###################################################################

###################################################################
#
# SELENIUM GRID ONLY OPTIONS BELOW HERE
#
###################################################################

